config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount PostgresqlLoStreamer::Engine => "/picture_image"
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    authenticated :user do
      root 'users#show_profile', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get '/profile', to: 'users#show_profile'


  #Static pages
  get '/help_page', to: 'static_pages#help_page'
  get '/about', to: 'static_pages#about'

  #Dictionaries
  get '/dictionaries', to: 'static_pages#dictionaries'
  get '/units_search', to: 'static_pages#units_search'
  get '/species_search', to: 'static_pages#species_search'
  get '/diseases_search', to: 'static_pages#diseases_search'
  get '/treatments_search', to: 'static_pages#treatments_search'
  get '/medocs_search', to: 'static_pages#medocs_search'

  get '/searchas_search', to: 'searchas#searchas_search'
  resources :units, only: [ :new, :create, :edit, :update ]
  resources :diseases, only: [ :new, :create, :edit, :update ]
  resources :treatments, only: [ :new, :create, :edit, :update ]
  resources :species, only: [ :new, :create, :edit, :update ]
  resources :medocs, only: [ :new, :create, :edit, :update ]
  resources :searchas, only: [ :index ]
  resources :animals , only: [ :index, :show, :new, :create, :edit, :update ]

  get '/proprios_search', to: 'proprios#proprios_search'
  resources :veterinarians, only: [ :index, :show, :new, :create, :edit, :update ]
  resources :proprios, only: [ :index, :show, :new, :create, :edit, :update ] do
   resources :animals , only: [ :index, :show, :new, :create, :edit, :update ]
   resources :medical_records, only: [ :index, :show, :new, :create, :edit, :update ]
   resources :hospits, only: [ :index, :show, :new, :create, :edit, :update ]
   resources :pictures, only: [ :index, :show, :new, :create, :edit, :update ]

  end
  resources :users, only: [ :index, :show, :new, :create, :edit, :update ] do
#    resources :animals , only: [ :index, :show, :new, :create, :edit, :update ]
#    get '/proprios/:proprio_id/animals/new', to: 'animals#new'
    resources :veterinarians, only: [ :index, :show, :new, :create, :edit, :update ]
    get '/veterinarians', to: 'veterinarians#index_veterinarians'
    get '/veterinarians/:id/calendar', to: 'veterinarians#show_calendar', as: 'veterinarian_calendar'
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  helper_method :sort_column, :sort_direction

  before_action :authenticate_veterinarian!, except: [ :help_page, :about ]

  def dictionaries
    case params[:tab]
      when 'units' then @units = Unit.order(sort_column + " " + sort_direction).paginate(page: params[:units_page], per_page: 8)
      when 'species' then @species = Species.order(sort_column + " " + sort_direction).paginate(page: params[:species_page], per_page: 8)
      when 'diseases' then @diseases = Disease.order(sort_column + " " + sort_direction).paginate(page: params[:diseases_page], per_page: 8)
      when 'treatments' then @treatments = Treatment.order(sort_column + " " + sort_direction).paginate(page: params[:treatments_page], per_page: 8)
      when 'medocs' then @medocs = Medoc.order(sort_column + " " + sort_direction).paginate(page: params[:medocs_page], per_page: 8)
    end
  end

  def units_search
    @units = Unit.search(params[:search]).order(sort_column + " " + sort_direction).paginate(page: params[:units_page], per_page: 8)
    params[:tab] = 'units'
  end

  def species_search
    @species = Species.search(params[:search]).order(sort_column + " " + sort_direction).paginate(page: params[:species_page], per_page: 8)
    params[:tab] = 'species'
  end

  def diseases_search
    @diseases = Disease.search(params[:search]).order(sort_column + " " + sort_direction).paginate(page: params[:diseases_page], per_page: 8)
    params[:tab] = 'diseases'
  end

  def treatments_search
    @treatments = Treatment.search(params[:search]).order(sort_column + " " + sort_direction).paginate(page: params[:treatments_page], per_page: 8)
    params[:tab] = 'treatments'
  end

  def medocs_search
    @medocs = Medoc.search(params[:search]).order(sort_column + " " + sort_direction).paginate(page: params[:medocs_page], per_page: 8)
    params[:tab] = 'medocs'
  end

  def help_page
  end

  def about
  end

  private

    def sort_column
      case params[:tab]
        when 'units' then Unit.column_names.include?(params[:sort]) ? params[:sort] : "name"
        when 'species' then Species.column_names.include?(params[:sort]) ? params[:sort] : "name"
        when 'diseases' then Disease.column_names.include?(params[:sort]) ? params[:sort] : "name"
        when 'treatments' then Treatment.column_names.include?(params[:sort]) ? params[:sort] : "name"
        when 'medocs' then Medoc.column_names.include?(params[:sort]) ? params[:sort] : "name"
        else 'name'
      end
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/_dict.html.haml
.panel.panel-default
  .panel-heading Dictionnaires
  .panel-body#static_pages
    %ul.nav.nav-tabs
      %li{:class => ('active' if params[:tab] == 'species')}
        = link_to 'Espèces', dictionaries_path(tab: 'species')
      %li{:class => ('active' if params[:tab] == 'treatments')}
        = link_to 'Traitements', dictionaries_path(tab: 'treatments')
      %li{:class => ('active' if params[:tab] == 'diseases')}
        = link_to 'Maladies/Acte prophylo', dictionaries_path(tab: 'diseases')
      %li{:class => ('active' if params[:tab] == 'units')}
        = link_to 'Unités', dictionaries_path(tab: 'units')
      %li{:class => ('active' if params[:tab] == 'medocs')}
        = link_to 'Médicaments listés', dictionaries_path(tab: 'medocs')

    .tab-content
      #species.tab-pane{:class => ('active' if params[:tab] == 'species')}
        - if params[:tab] == 'species'
          = render 'species'
      #treatments.tab-pane{:class => ('active' if params[:tab] == 'treatments')}
        - if params[:tab] == 'treatments'
          = render 'treatments'
      #diseases.tab-pane{:class => ('active' if params[:tab] == 'diseases')}
        - if params[:tab] == 'diseases'
          = render 'diseases'
      #units.tab-pane{:class => ('active' if params[:tab] == 'units')}
        - if params[:tab] == 'units'
          = render 'units'
      #medocs.tab-pane{:class => ('active' if params[:tab] == 'medocs')}
        - if params[:tab] == 'medocs'
          = render 'medocs'

app/views/static_pages/_diseases.html.haml
= form_tag diseases_search_path, method: :get do
  = hidden_field_tag :direction, params[:direction]
  = hidden_field_tag :sort, params[:sort]
  = hidden_field_tag :tab, 'diseases'
  .form-inline
    = text_field_tag :search, params[:search], placeholder: 'Entrez le sujet', class: 'form-control'
    = submit_tag "Rechercher", name: nil, class: 'btn btn-default'

    .pull-right
      = link_to 'Ajouter maladie', new_disease_path, class: "btn btn-default"

- if @diseases.empty?
  .alert.alert-warning.table-warning Aucun enregistrement.
- else
  %table.table.table-striped
    %thead
      %tr
        %th= sortable 'name', "Nom"
        %th= sortable 'status', "Status"
        %th
    %tbody
      - @diseases.each do |disease|
        %tr
          %td= change_blank_to_dash(disease.name)
          %td= change_blank_to_dash(disease.status)
          %td
            .pull-right
              = link_to icon('edit'), edit_disease_path(disease), title: 'Modifier', class: "btn btn-default"

  .flickr_pagination
    = will_paginate @diseases, param_name: 'diseases_page'

app/views/static_pages/_medocs.html.haml
= form_tag medocs_search_path, method: :get do
  = hidden_field_tag :direction, params[:direction]
  = hidden_field_tag :sort, params[:sort]
  = hidden_field_tag :tab, 'medocs'
  .form-inline
    = text_field_tag :search, params[:search], placeholder: 'Entrez le nom du médicament', class: 'form-control'
    = submit_tag "Recherche", name: nil, class: 'btn btn-default'

    .pull-right
      = link_to 'Ajouter', new_medoc_path, class: "btn btn-default"

- if @medocs.empty?
  .alert.alert-warning.table-warning Aucun enregistrement.
- else
  %table.table.table-striped
    %thead
      %tr
        %th= sortable 'name', "Nom"
        %th= sortable 'status', "Status"
        %th
    %tbody
      - @medocs.each do |medoc|
        %tr
          %td= change_blank_to_dash(medoc.name)
          %td= change_blank_to_dash(medoc.status)
          %td
            .pull-right
              = link_to icon('edit'), edit_medoc_path(medoc), title: 'Modifier', class: "btn btn-default"

  .flickr_pagination
    = will_paginate @medocs, param_name: 'medocs_page'

app/views/static_pages/_species.html.haml
= form_tag species_search_path, method: 'get' do
  = hidden_field_tag :direction, params[:direction]
  = hidden_field_tag :sort, params[:sort]
  = hidden_field_tag :tab, 'species'
  .form-inline
    = text_field_tag :search, params[:search], placeholder: 'Entrez le nom de espèce', class: 'form-control'
    = submit_tag "Rechercher", name: nil, class: 'btn btn-default'

    .pull-right
      = link_to 'Ajouter une espèce', new_species_path, class: "btn btn-default"

- if @species.empty?
  .alert.alert-warning.table-warning Aucun enregistrement.
- else
  %table.table.table-striped
    %thead
      %tr
        %th= sortable 'name', "Nom"
        %th= sortable 'status', "Status"
        %th
    %tbody
      - @species.each do |s|
        %tr
          %td= change_blank_to_dash(s.name)
          %td= change_blank_to_dash(s.status)
          %td
            .pull-right
              = link_to icon('edit'), edit_species_path(s), title: 'Modifier', class: "btn btn-default"

  .flickr_pagination
    = will_paginate @species, param_name: 'species_page'

app/views/static_pages/_treatments.html.haml
= form_tag treatments_search_path, method: :get do
  = hidden_field_tag :direction, params[:direction]
  = hidden_field_tag :sort, params[:sort]
  = hidden_field_tag :tab, 'treatments'
  .form-inline
    = text_field_tag :search, params[:search], placeholder: 'Entrez un nom de traitement', class: 'form-control'
    = submit_tag "Recherche", name: nil, class: 'btn btn-default'

    .pull-right
      = link_to 'Ajoutez un traitement', new_treatment_path, class: "btn btn-default"

- if @treatments.empty?
  .alert.alert-warning.table-warning Pas d'enregistrement.
- else
  %table.table.table-striped
    %thead
      %tr
        %th= sortable 'name', "Nom"

        %th= sortable 'status', "Status"
        %th= sortable 'description', "Description"
        %th
    %tbody
      - @treatments.each do |treatment|
        %tr
          %td= change_blank_to_dash(treatment.name)

          %td= change_blank_to_dash(treatment.status)
          %td= change_blank_to_dash(treatment.description)
          %td
            .pull-right
              = link_to icon('edit'), edit_treatment_path(treatment), title: 'Modifier', class: "btn btn-default"

  .flickr_pagination
    = will_paginate @treatments, param_name: 'treatments_page'

app/views/static_pages/_units.html.haml
= form_tag units_search_path, method: :get do
  = hidden_field_tag :direction, params[:direction]
  = hidden_field_tag :sort, params[:sort]
  = hidden_field_tag :tab, 'units'
  .form-inline
    = text_field_tag :search, params[:search], placeholder: 'Entrez le nom de unité', class: 'form-control'
    = submit_tag "Recherche", name: nil, class: 'btn btn-default'

    .pull-right
      = link_to 'Ajouter unité', new_unit_path, class: "btn btn-default"

- if @units.empty?
  .alert.alert-warning.table-warning Aucun enregistrement.
- else
  %table.table.table-striped
    %thead
      %tr
        %th= sortable 'name', "Nom"
        %th= sortable 'status', "Status"
        %th
    %tbody
      - @units.each do |unit|
        %tr
          %td= change_blank_to_dash(unit.name)
          %td= change_blank_to_dash(unit.status)
          %td
            .pull-right
              = link_to icon('edit'), edit_unit_path(unit), title: 'Modifier', class: "btn btn-default"

  .flickr_pagination
    = will_paginate @units, param_name: 'units_page'

app/views/static_pages/about.html.haml
.panel.panel-default
  .panel-heading Contact
  .panel-body
    .row
      .col-md-8
        %table.table
          %thead.table-centered
            %tr
              %th Accéder à la clinique
          %tbody.table-centered
            %tr
              %td= link_to image_tag("map.png", width: '600'), image_path('map.png')
      .col-md-4
        %table.table
          %thead.table-centered
            %tr
              %th Information de contact
          %tbody.table-centered
            %tr
              %td
            %tr
              %td Clinique Vétérinaire de Saint Junien
            %tr
              %td ZI de la Croix Blanche
            %tr
              %td 87200 SAINT JUNIEN
            %tr
              %td tel. 05 55 02 17 52
            %tr
              %td 
            %tr
              %td fax 05 55 02 68 28
            %tr
              %td NIP: 1234567890
            %tr
              %td clinvet-stjunien@wanadoo.Fr

app/views/static_pages/dictionaries.html.haml
= render 'dict'

app/views/static_pages/diseases_search.html.haml
= render 'dict'

app/views/static_pages/help_page.html.haml
.row
  .col-md-2
  .col-md-8
    .panel.panel-default
      .panel-heading Aide
      .panel-body
        - if current_user.nil?
          .alert.alert-success.help_page= link_to "Mot de passe oublié.", new_password_path(User)
          .alert.alert-success.help_page.help_page= link_to "Envoyez instructions pour dévérouiller votre compte.", new_unlock_path(User)
        .alert.alert-success.help_page= link_to "Re-confirmer email.", new_confirmation_path(User)
  .col-md-2

app/views/static_pages/medocs_search.html.haml
= render 'dict'

app/views/static_pages/species_search.html.haml
= render 'dict'

app/views/static_pages/treatments_search.html.haml
= render 'dict'

app/views/static_pages/units_search.html.haml
= render 'dict'