config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount PostgresqlLoStreamer::Engine => "/picture_image"
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    authenticated :user do
      root 'users#show_profile', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get '/profile', to: 'users#show_profile'


  #Static pages
  get '/help_page', to: 'static_pages#help_page'
  get '/about', to: 'static_pages#about'

  #Dictionaries
  get '/dictionaries', to: 'static_pages#dictionaries'
  get '/units_search', to: 'static_pages#units_search'
  get '/species_search', to: 'static_pages#species_search'
  get '/diseases_search', to: 'static_pages#diseases_search'
  get '/treatments_search', to: 'static_pages#treatments_search'
  get '/medocs_search', to: 'static_pages#medocs_search'

  get '/searchas_search', to: 'searchas#searchas_search'
  resources :units, only: [ :new, :create, :edit, :update ]
  resources :diseases, only: [ :new, :create, :edit, :update ]
  resources :treatments, only: [ :new, :create, :edit, :update ]
  resources :species, only: [ :new, :create, :edit, :update ]
  resources :medocs, only: [ :new, :create, :edit, :update ]
  resources :searchas, only: [ :index ]
  resources :animals , only: [ :index, :show, :new, :create, :edit, :update ]

  get '/proprios_search', to: 'proprios#proprios_search'
  resources :veterinarians, only: [ :index, :show, :new, :create, :edit, :update ]
  resources :proprios, only: [ :index, :show, :new, :create, :edit, :update ] do
   resources :animals , only: [ :index, :show, :new, :create, :edit, :update ]
   resources :medical_records, only: [ :index, :show, :new, :create, :edit, :update ]
   resources :hospits, only: [ :index, :show, :new, :create, :edit, :update ]
   resources :pictures, only: [ :index, :show, :new, :create, :edit, :update ]

  end
  resources :users, only: [ :index, :show, :new, :create, :edit, :update ] do
#    resources :animals , only: [ :index, :show, :new, :create, :edit, :update ]
#    get '/proprios/:proprio_id/animals/new', to: 'animals#new'
    resources :veterinarians, only: [ :index, :show, :new, :create, :edit, :update ]
    get '/veterinarians', to: 'veterinarians#index_veterinarians'
    get '/veterinarians/:id/calendar', to: 'veterinarians#show_calendar', as: 'veterinarian_calendar'
  end
end

app/models/veterinarian.rb
class Veterinarian < ActiveRecord::Base
  belongs_to :user
  has_many :medical_records
  has_many :hospits
  belongs_to :user
  has_many :vacations
  has_one :working_day

  accepts_nested_attributes_for :working_day

  validates_presence_of :title, :pwz

  def custom_label_method
    "##{id} #{title} #{user.try(:decorate).try(:full_name)}, pwz: #{pwz}"
  end

  def next_vacation
    vacation = vacations.where("start >= :d OR \"end\" >= :d", { d: Date.today }).order(:start).first
    vacation.nil? ? '' : "#{vacation.start} - #{vacation.end}"
  end

  def working_today?(date)
    if working_day.nil?
      false
    else
      case date.wday
      when 0
        working_day.sunday?
      when 1
        working_day.monday?
      when 2
        working_day.tuesday?
      when 3
        working_day.wednesday?
      when 4
        working_day.thursday?
      when 5
        working_day.friday?
      when 6
        working_day.saturday?
      end
    end
  end

  def on_vacation?(date)
    if vacations.nil?
      false
    else
      vacations.each do |vacation|
        if vacation.start <= date && vacation.end >= date
          return true
        end
      end

      return false
    end
  end
end

app/controllers/veterinarians_controller.rb
class VeterinariansController < ApplicationController
  helper_method :sort_column, :sort_direction

  expose(:veterinarians) { User.where(role: 0).order(sort_column + " " + sort_direction).paginate(page: params[:page], per_page: 8) }
#  expose(:user) { User.find(params[:user_id]) }

  def index
    if params[:search]
      self.veterinarians = Veterinarian.search(params[:search], params[:user_id]).order(sort_column + " " + sort_direction).paginate(page: params[:page], per_page: 8)
    end
  end

  def show_calendar
    @date = params[:date] ? Date.parse(params[:date]) : Date.today
    @veterinarian = Veterinarian.find(params[:id])
  end

  def index_veterinarians
    if params[:search]
      self.veterinarians = Veterinarian.search(params[:search], params[:user_id]).order(sort_column + " " + sort_direction).paginate(page: params[:page], per_page: 8)
    end
  end

  private

    def sort_column
      User.column_names.include?(params[:sort]) ? params[:sort] : "last_name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/veterinarians_helper.rb
module VeterinariansHelper
end

app/views/veterinarians/_search_form.html.haml
= form_tag veterinarians_path, method: :get do
  = hidden_field_tag :direction, params[:direction]
  = hidden_field_tag :sort, params[:sort]
  .form-inline
    = text_field_tag :search, params[:search], placeholder: 'Entrez le nom du vétérinaire', class: 'form-control', size: 35
    = submit_tag "Recherche", name: nil, class: 'btn btn-default'

app/views/veterinarians/_search_veterinarians_form.html.haml
= form_tag user_veterinarians_path, method: :get do
  = hidden_field_tag :direction, params[:direction]
  = hidden_field_tag :sort, params[:sort]
  .form-inline
    = text_field_tag :search, params[:search], placeholder: 'Entrez le nom du vétérinaire', class: 'form-control', size: 35
    = submit_tag "Recherche", name: nil, class: 'btn btn-default'

app/views/veterinarians/index.html.haml
.panel.panel-default
  .panel-heading Vétérinaires
  .panel-body
    = render 'search_form'
    - if veterinarians.empty?
      .alert.alert-warning.table-warning Aucun vétérinaire.
    - else
      %table.table.table-striped
        %thead
          %tr
            %th Titre
            %th= sortable 'first_name', "Prénom"
            %th= sortable 'last_name', "Nom"
            %th= sortable 'phone_number', "Téléphone"
            %th Spécialité
            %th Jour d'admission
            %th Vacances les plus proches

        %tbody
          - veterinarians.each do |veterinarian|
            %tr
              %td= change_blank_to_dash(veterinarian.try(:veterinarian).try(:title))
              %td= change_blank_to_dash(veterinarian.first_name)
              %td= change_blank_to_dash(veterinarian.last_name)
              %td= change_blank_to_dash(veterinarian.phone_number)
              %td= change_blank_to_dash(veterinarian.try(:veterinarian).try(:specialization))
              %td= change_blank_to_dash(veterinarian.try(:veterinarian).try(:working_day).try(:decorate).try(:print_working_days))
              %td= change_blank_to_dash(veterinarian.try(:veterinarian).try(:next_vacation))
      .flickr_pagination
        = will_paginate veterinarians

app/views/veterinarians/index_veterinarians.html.haml
.panel.panel-default
  .panel-heading Vétérinaires
  .panel-body
    = render 'search_veterinarians_form'
    - if veterinarians.empty?
      .alert.alert-warning.table-warning Aucun vétérinaire.
    - else
      %table.table.table-striped
        %thead
          %tr
            %th= sortable 'title', "Titre"
            %th= sortable 'first_name', "Prénom"
            %th= sortable 'last_name', "Nom"
            %th= sortable 'phone_number', "Téléphone"
            %th= sortable 'specialization', "Spécialité"
            %th= sortable 'working_day', "Jours de travail"
            %th= sortable 'next_vacation', "Prochaine vacances"
            %th

        %tbody
          - veterinarians.each do |veterinarian|
            %tr
              %td= change_blank_to_dash(veterinarian.try(:veterinarian).try(:title))
              %td= change_blank_to_dash(veterinarian.first_name)
              %td= change_blank_to_dash(veterinarian.last_name)
              %td= change_blank_to_dash(veterinarian.phone_number)
              %td= change_blank_to_dash(veterinarian.try(:veterinarian).try(:specialization))
              %td= change_blank_to_dash(veterinarian.try(:veterinarian).try(:working_day).try(:decorate).try(:print_working_days))
              %td= change_blank_to_dash(veterinarian.try(:veterinarian).try(:next_vacation))
              %td
                .pull-right
                  = link_to icon('calendar'), user_veterinarian_calendar_path(params[:user_id], veterinarian.try(:veterinarian)), title: 'Afficher le calendrier', class: "btn btn-default"

      .flickr_pagination
        = will_paginate veterinarians

app/views/veterinarians/show_calendar.html.haml
.panel.panel-default
  .panel-heading Calendrier
  .panel-body
    #veterinarians
      %h2#month
        = link_to icon('chevron-left'), date: @date.prev_month
        = l(@date, format: :short)
        = link_to icon('chevron-right'), date: @date.next_month
      = calendar @date do |date|
        = date.day
        %br
        - if Date.today <= date
          - if @veterinarian.on_vacation?(date)
            = link_to "Vacances", '#', class: "btn btn-warning disabled"
          - else
            = link_to "Journée de repos", '#', class: "btn btn-warning disabled"
        - else
          %h4= "-"