config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount PostgresqlLoStreamer::Engine => "/picture_image"
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    authenticated :user do
      root 'users#show_profile', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get '/profile', to: 'users#show_profile'


  #Static pages
  get '/help_page', to: 'static_pages#help_page'
  get '/about', to: 'static_pages#about'

  #Dictionaries
  get '/dictionaries', to: 'static_pages#dictionaries'
  get '/units_search', to: 'static_pages#units_search'
  get '/species_search', to: 'static_pages#species_search'
  get '/diseases_search', to: 'static_pages#diseases_search'
  get '/treatments_search', to: 'static_pages#treatments_search'
  get '/medocs_search', to: 'static_pages#medocs_search'

  get '/searchas_search', to: 'searchas#searchas_search'
  resources :units, only: [ :new, :create, :edit, :update ]
  resources :diseases, only: [ :new, :create, :edit, :update ]
  resources :treatments, only: [ :new, :create, :edit, :update ]
  resources :species, only: [ :new, :create, :edit, :update ]
  resources :medocs, only: [ :new, :create, :edit, :update ]
  resources :searchas, only: [ :index ]
  resources :animals , only: [ :index, :show, :new, :create, :edit, :update ]

  get '/proprios_search', to: 'proprios#proprios_search'
  resources :veterinarians, only: [ :index, :show, :new, :create, :edit, :update ]
  resources :proprios, only: [ :index, :show, :new, :create, :edit, :update ] do
   resources :animals , only: [ :index, :show, :new, :create, :edit, :update ]
   resources :medical_records, only: [ :index, :show, :new, :create, :edit, :update ]
   resources :hospits, only: [ :index, :show, :new, :create, :edit, :update ]
   resources :pictures, only: [ :index, :show, :new, :create, :edit, :update ]

  end
  resources :users, only: [ :index, :show, :new, :create, :edit, :update ] do
#    resources :animals , only: [ :index, :show, :new, :create, :edit, :update ]
#    get '/proprios/:proprio_id/animals/new', to: 'animals#new'
    resources :veterinarians, only: [ :index, :show, :new, :create, :edit, :update ]
    get '/veterinarians', to: 'veterinarians#index_veterinarians'
    get '/veterinarians/:id/calendar', to: 'veterinarians#show_calendar', as: 'veterinarian_calendar'
  end
end

app/models/animal.rb
class Animal < ActiveRecord::Base
  enum gender: [ :male, :femelle, :F_neutered, :M_neutered ]
  enum statut: [ :vivant, :DCD ]

  belongs_to :proprio
  belongs_to :species
  has_many :pictures
  has_and_belongs_to_many :medical_records
  has_and_belongs_to_many :hospits
  validates_presence_of :gender, :species_id

  def custom_label_method
    "##{id} ID: #{id_number}, Nom: #{name}, Age: #{trim(age)}, Nombre: #{amount}, Espèce: #{species.try(:name)}"
  end

  private

  def self.search(search)
      joins(:proprio).where("(lower(animals.name) LIKE ? or lower(animals.id_number) LIKE ?)", "%#{search}%", "%#{search}%")
  end

#def self.search(query)
#  where("(lower(id_number) like :q OR lower(name) like :q", { q: "%#{query}%" })
#end

    def trim(num)
      if num.blank?
        "Aucun"
      else
        i, f = num.to_i, num.to_f
        i == f ? i : f
      end
    end
end

app/controllers/animals_controller.rb
# coding: utf-8
class AnimalsController < ApplicationController
  helper_method :sort_column, :sort_direction

  before_action :authenticate_user!, only: [ :index, :show ]
  before_action :authenticate_veterinarian!, only: [ :new, :create, :edit, :update ]
  expose(:proprio) { Proprio.find(params[:proprio_id]) }
  expose(:medical_record) { Medical_record.find(params[:Medical_record_id]) }
  expose(:animal, attributes: :animal_params)
  expose(:animals) { proprio.animals.order(sort_column + " " + sort_direction).paginate(page: params[:page], per_page: 8) }

#  def searchas
#    @animals = Animal.search(params[:search]).order(sort_column + " " + sort_direction).paginate(page: params[:proprios_page], per_page: 20)
#  end

  def index
    if params[:search]
      self.animals = Animal.search(params[:search]).order(sort_column + " " + sort_direction).paginate(page: params[:page], per_page: 8)
    end
  end

  def show
    @hospits = proprio.hospits.order(created_at: :desc).limit(8)
    @pictures = animal.pictures.order(:created_at).paginate(page: params[:pictures_page], per_page: 10)
    @medical_records = animal.medical_records.order(:created_at).paginate(page: params[:medical_records_page], per_page: 10)
#    @animal1 = animal.medical_records.order(:id).map { |animal|  [ "Nom: #{animal.name}"] }
  end

  def new
    @species = Species.order(:name).where(:status => 'actif')
  end

  def create
    animal.weight = change_comma_to_period(params[:animal][:weight])
    animal.age = change_comma_to_period(params[:animal][:age])
    if animal.save
      redirect_to proprio_animals_path, notice: 'Animal crée avec succès.'
    else
      @species = Species.order(:name).where(status: "actif")
      render :new
    end
  end

  def edit
    @species = Species.order(:name).map do |s|
      ["#{s.name} #{"(Inactif)" if s.inactif?}", s.id]
    end
  end

  def update
    animal.weight = change_comma_to_period(params[:animal][:weight])
    animal.age = change_comma_to_period(params[:animal][:age])
    if animal.save
      redirect_to proprio_animals_path, notice: 'Animal modifié avec succès.'
    else
      @species = Species.order(:name).map { |s| [ "#{s.name} #{"(Inactif)" if s.inactif?}", s.id ] }
      render :edit
    end
  end

  private

    def animal_params
      params.require(:animal).permit(:id_number, :name, :birth_date, :statut,
                                     :weight, :gender, :age, :description,
                                     :proprio_id, :species_id)
    end

    def sort_column
      Animal.column_names.include?(params[:sort]) ? params[:sort] : "id_number"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/animals_helper.rb
module AnimalsHelper
end

app/views/animals/_form.html.haml
= simple_form_for [ proprio, animal ] do |f|
  = f.error_notification
  .form-inputs
    .row
      .col-md-1
      .col-md-3
        = f.input :id_number, label: 'N° indentification', placeholder: 'N° identif.', autofocus: true
        = f.input :birth_date, label: 'Date de naissance', placeholder: 'dd/mm/aaaa', as: :date_picker
      .col-md-3
        = f.input :name, label: 'Nom', placeholder: 'Mettre le nom'
        = f.input :species_id, label: 'Espèce', collection: @species
      .col-md-2
        = f.input :gender, label: 'Sexe'
        = f.input :statut, label: 'Statut'
      .col-md-1
    .row
      .col-md-1
      .col-md-10
        = f.input :description, label: 'Description', placeholder: 'couleur, caractéristiques physiques,race'
      .col-md-1
  .row
    .form-actions
      .col-md-1
      .col-md-5
        = link_to "Annuler", proprio_animals_path, class: "btn btn-default"
      .col-md-5
        .pull-right
          = f.button :submit, "Sauvegarder", class: "btn btn-default"
      .col-md-1

app/views/animals/_search_form.html.haml
= form_tag proprio_animals_path, method: :get do
  = hidden_field_tag :direction, params[:direction]
  = hidden_field_tag :sort, params[:sort]
  .form-inline
    = text_field_tag :search, params[:search], placeholder: 'identification ou nom animal', class: 'form-control', size: 45
    = submit_tag "Recherche", name: nil, class: 'btn btn-default'

app/views/animals/edit.html.haml
.panel.panel-default
  .panel-heading Modifier animal
  .panel-body
    = render 'form'

app/views/animals/index.html.haml
.panel.panel-default
  .panel-heading Listing animaux
  .panel-body
    = render 'search_form'
    - if animals.empty?
      .alert.alert-warning.table-warning Pas d'animaux.
    - else
      %table.table.table-striped
        %thead
          %tr
            %th Nom
            %th= sortable 'gender', "Sexe"
            %th= sortable 'statut', "Statut"
            %th Espèce
            %th= sortable 'id_number', "N° indentification"
            %th.btn-row-3
        %tbody
          - animals.each do |animal|
            %tr
              %td= change_blank_to_dash(animal.name.capitalize)
              %td= change_blank_to_dash(animal.gender)
              %td= change_blank_to_dash(animal.statut)
              %td= change_blank_to_dash(animal.try(:species).try(:name))
              %td= change_blank_to_dash(animal.id_number)
              %td
                .pull-right
                  = link_to "H", proprio_animal_path(proprio, animal.id, :format => 'pdf'), title: 'Historique', class: "btn btn-default"
                  = link_to icon('list-alt'), proprio_animal_path(proprio, animal), title: 'Animal', class: "btn btn-default"
                  = link_to icon('edit'), edit_proprio_animal_path(proprio, animal), title: 'Modifier', class: "btn btn-default"

    .pull-right
      = link_to "Nouvel animal", new_proprio_animal_path(proprio), class: "btn btn-default"
      = link_to "Vers le profil du propriétaire", proprio_path(proprio), class: "btn btn-default"

    .flickr_pagination
      = will_paginate animals

app/views/animals/new.html.haml
.panel.panel-default
  .panel-heading Nouvel animal
  .panel-body
    = render 'form'

app/views/animals/show.html.haml
.panel.panel-default
  .panel-heading= "Animal nr #{change_blank_to_dash(animal.id_number)}"
  .panel-body
    .panel.panel-info
      .panel-heading Données de l'animal
      .panel-body
        .row
          .col-md-1
          .col-md-5
            %table.table
              %thead
                %tr
                  %th
              %tbody
                %tr
                  %th N° identification:
                  %td= change_blank_to_dash(animal.id_number)
                %tr
                  %th Nom:
                  %td= change_blank_to_dash(animal.name.capitalize)
                %tr
                  %th Date de naissance:
                  %td= change_blank_to_dash(animal.birth_date)
                %tr
                  %th Statut:
                  %td= change_blank_to_dash(animal.statut)
                %tr
                  %td
          .col-md-5
            %table.table
              %thead
                %tr
                  %th
              %tbody
                %tr
                  %th Sexe:
                  %td= change_blank_to_dash(animal.gender)
                %tr
                  %th Espèce:
                  %td= change_blank_to_dash(animal.try(:species).try(:name))
                %tr
                  %th Description:
                  %td= change_blank_to_dash(animal.description)
                %tr
                  %td
          .col-md-1

    .pull-right
      = link_to "Historique", proprio_animal_path(proprio, animal.id, :format => 'pdf'), title: 'Historique', class: "btn btn-default"
      = link_to "Ajouter consult", new_proprio_medical_record_path(proprio), class: "btn btn-default"
      = link_to "Ajouter hospit", new_proprio_hospit_path(proprio), class: "btn btn-default"
      = link_to "Ajouter image", new_proprio_picture_path(proprio), class: "btn btn-default"
      = link_to "Retour listing", proprio_animals_path(proprio), class: "btn btn-default"

.panel.panel-default
  .panel-heading Fichiers consultation
  .panel-body
    .pull-right
      = link_to "Nouvelle consult", new_proprio_medical_record_path(proprio), class: "btn btn-default"
    - if @medical_records.empty?
      .alert.alert-warning.table-warning Pas de fiche.
    - else
      %table.table.table-striped
        %thead
          %tr
            %th Description consultation
            %th Vétérinaire
            %th Date
            %th

        %tbody
          - @medical_records.each do |medical_record|
            %tr
              %td= change_blank_to_dash(medical_record.decorate.consultation)
              %td= change_blank_to_dash(medical_record.veterinarian.user.last_name)
              %td= change_blank_to_dash(medical_record.created_at.to_date)
              %td

                .pull-right
                  = link_to icon('list-alt'), proprio_medical_record_path(proprio, medical_record), title: 'Détails', class: "btn btn-default"
                  = link_to icon('edit'), edit_proprio_medical_record_path(proprio, medical_record), title: 'Modifier', class: "btn btn-default"
          .flickr_pagination
            = will_paginate @medical_records, param_name: 'medical_records_page'
    .pull-right
      = link_to "Nouvelle consult", new_proprio_medical_record_path(proprio), class: "btn btn-default"

.panel.panel-default
  .panel-heading Hospitalisation
  .panel-body
    - if @hospits.empty?
      .alert.alert-warning.table-warning Pas de fichier.
    - else
      %table.table.table-striped
        %thead
          %tr
            %th Cause hospitalisation
            %th Vétérinaire
            %th Observations
            %th.date-row Date d'entrée
            %th.btn-row-2

        %tbody
          - @hospits.each do |hospit|
            %tr
              %td= change_blank_to_dash(hospit.anamnesis)
              %td= change_blank_to_dash(hospit.veterinarian.user.last_name)
              %td= change_blank_to_dash(hospit.description)
              %td= change_blank_to_dash(hospit.created_at.to_date)
              %td
                .pull-right
                  = link_to icon('list-alt'), proprio_hospit_path(proprio, hospit), title: 'Détails', class: "btn btn-default"
                  = link_to icon('edit'), edit_proprio_hospit_path(proprio, hospit), title: 'Modifier', class: "btn btn-default"
    .pull-right
      = link_to "Nouvelle hospit", new_proprio_hospit_path(proprio), class: "btn btn-default"

.panel.panel-default
  .panel-heading Images de l'animal
  .panel-body
    - if @pictures.empty?
      Pas d'images.
    - else
      %table.table.table-striped
        %thead
          %tr
            %th Nom
            %th Image
            %th Description

        %tbody
          - @pictures.each do |picture|
            %tr
              %td= change_blank_to_dash(picture.name)
              %td= link_to image_tag(picture.image, width: 100), picture.image.url
              %td= change_blank_to_dash(picture.description)

      .flickr_pagination
        = will_paginate @pictures, param_name: 'pictures_page'
    .pull-right
      = link_to "Ajouter image", new_proprio_picture_path(proprio), class: "btn btn-default"

.pull-right
  = link_to "Ajouter consult", new_proprio_medical_record_path(proprio), class: "btn btn-default"
  = link_to "Ajouter hospit", new_proprio_hospit_path(proprio), class: "btn btn-default"
  = link_to "Ajouter image", new_proprio_picture_path(proprio), class: "btn btn-default"
  = link_to "Retour listing", proprio_animals_path(proprio), class: "btn btn-default"