config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  mount PostgresqlLoStreamer::Engine => "/picture_image"
  devise_for :users, controllers: { registrations: 'registrations' }

  devise_scope :user do
    authenticated :user do
      root 'users#show_profile', as: :authenticated_root
    end

    unauthenticated do
      root 'devise/sessions#new', as: :unauthenticated_root
    end
  end

  get '/profile', to: 'users#show_profile'


  #Static pages
  get '/help_page', to: 'static_pages#help_page'
  get '/about', to: 'static_pages#about'

  #Dictionaries
  get '/dictionaries', to: 'static_pages#dictionaries'
  get '/units_search', to: 'static_pages#units_search'
  get '/species_search', to: 'static_pages#species_search'
  get '/diseases_search', to: 'static_pages#diseases_search'
  get '/treatments_search', to: 'static_pages#treatments_search'
  get '/medocs_search', to: 'static_pages#medocs_search'

  get '/searchas_search', to: 'searchas#searchas_search'
  resources :units, only: [ :new, :create, :edit, :update ]
  resources :diseases, only: [ :new, :create, :edit, :update ]
  resources :treatments, only: [ :new, :create, :edit, :update ]
  resources :species, only: [ :new, :create, :edit, :update ]
  resources :medocs, only: [ :new, :create, :edit, :update ]
  resources :searchas, only: [ :index ]
  resources :animals , only: [ :index, :show, :new, :create, :edit, :update ]

  get '/proprios_search', to: 'proprios#proprios_search'
  resources :veterinarians, only: [ :index, :show, :new, :create, :edit, :update ]
  resources :proprios, only: [ :index, :show, :new, :create, :edit, :update ] do
   resources :animals , only: [ :index, :show, :new, :create, :edit, :update ]
   resources :medical_records, only: [ :index, :show, :new, :create, :edit, :update ]
   resources :hospits, only: [ :index, :show, :new, :create, :edit, :update ]
   resources :pictures, only: [ :index, :show, :new, :create, :edit, :update ]

  end
  resources :users, only: [ :index, :show, :new, :create, :edit, :update ] do
#    resources :animals , only: [ :index, :show, :new, :create, :edit, :update ]
#    get '/proprios/:proprio_id/animals/new', to: 'animals#new'
    resources :veterinarians, only: [ :index, :show, :new, :create, :edit, :update ]
    get '/veterinarians', to: 'veterinarians#index_veterinarians'
    get '/veterinarians/:id/calendar', to: 'veterinarians#show_calendar', as: 'veterinarian_calendar'
  end
end

app/models/picture.rb
class Picture < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  belongs_to :proprio
  belongs_to :animal
  has_and_belongs_to_many :medical_records

  validates_presence_of :name, :image, :animal_id

  def custom_label_method
    "##{id} #{name}"
  end

  private

    def self.search(query, proprio_id)
      where("(lower(name) like :q OR lower(description) like :q) AND user_id = :u", { q: "%#{query.downcase}%", u: proprio_id })
    end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  helper_method :sort_column, :sort_direction

#  before_action :authenticate_proprio!, only: [ :index, :show ]
  before_action :authenticate_veterinarian!, only: [ :new, :create, :edit, :update ]
  expose(:animal) { Animal.find(params[:animal_id]) }
  expose(:proprio) { Proprio.find(params[:proprio_id]) }
  expose(:picture, attributes: :picture_params)
  expose(:pictures) { proprio.pictures.order(sort_column + " " + sort_direction).paginate(page: params[:page], per_page: 8) }

  def index
    if params[:search]
      self.pictures = Picture.search(params[:search], params[:proprio_id]).order(sort_column + " " + sort_direction).paginate(page: params[:page], per_page: 8)
    end
  end

  def show
    @animals = Animal.where(proprio_id: proprio.id).map { |animal|  [ "Nom: #{animal.name}, Espèce: #{animal.try(:species).try(:name)}, Description: #{animal.description}", animal.id ] }
  end

  def new
    @animals = Animal.where(proprio_id: proprio.id).map { |animal|  [ "Nom: #{animal.name}, Espèce: #{animal.try(:species).try(:name)}, Description: #{animal.description}", animal.id ] }
  end

  def create
    if picture.save
      redirect_to proprio_pictures_path(proprio), notice: 'La photo a été crée avec succès.'
    else
      @animals = Animal.where(proprio_id: proprio.id).map { |animal|  [ "Nom: #{animal.name}, Espèce: #{animal.try(:species).try(:name)}, Description: #{animal.description}", animal.id ] }
      render :new
    end
  end

  def edit
    @animals = Animal.where(proprio_id: proprio.id).map { |animal| [ "Nom: #{animal.name}, Espèce: #{animal.try(:species).try(:name)}, Description: #{animal.description}", animal.id ] }
  end

  def update
    if picture.save
      redirect_to proprio_pictures_path(proprio), notice: 'La photo a été modifiée avec succès.'
    else
      @animals = Animal.where(proprio_id: proprio.id).map { |animal| [ "Nom: #{animal.name}, Espèce: #{animal.try(:species).try(:name)}, Description: #{animal.description}", animal.id ] }
      render :edit
    end
  end

  private

    def picture_params
      params.require(:picture).permit(:name, :description, :proprio_id, :image, :animal_id)
    end

    def sort_column
      Picture.column_names.include?(params[:sort]) ? params[:sort] : "name"
    end

    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/pictures/_form.html.haml
= simple_form_for [ proprio, picture ] do |f|
  = f.error_notification
  .row
    .form-inputs
      .col-md-1
      .col-md-5
        = f.input :name, label: 'Nom', placeholder: 'Tapez un nom de fichier', autofocus: true
        = f.input :description, label: 'Description', placeholder: 'Entrez une description de la photo'
        = f.input :animal_id, label: 'Animal', collection: @animals
      .col-md-5
        = f.input :image, label: 'Image', as: :image_preview
      .col-md-1
  .row
    .col-md-1
    .col-md-10
      .form-actions
        .pull-right
          = f.button :submit, "Sauvegarder", class: "btn btn-default"
        = link_to "Annuler", proprio_pictures_path(proprio), class: "btn btn-default"
    .col-md-1

app/views/pictures/_search_form.html.haml
= form_tag proprio_pictures_path(proprio), method: :get do
  = hidden_field_tag :direction, params[:direction]
  = hidden_field_tag :sort, params[:sort]
  .form-inline
    = text_field_tag :search, params[:search], placeholder: 'Entrez le nom ou la description', class: 'form-control', size: 27
    = submit_tag "Recherche", name: nil, class: 'btn btn-default'

app/views/pictures/edit.html.haml
.panel.panel-default
  .panel-heading Edition images
  .panel-body
    = render 'form'

app/views/pictures/index.html.haml
.panel.panel-default
  .panel-heading Images
  .panel-body
    = render 'search_form'
    - if pictures.empty?
      .alert.alert-warning.table-warning Aucune image.
    - else
      %table.table.table-striped
        %thead
          %tr
            %th= sortable 'name', "Nom"
            %th Animal
            %th Image
            %th= sortable 'description', "Description"
            %th.btn-row-2

        %tbody
          - pictures.each do |picture|
            %tr
              %td= change_blank_to_dash(picture.name)
              %td= change_blank_to_dash(picture.animal.name)
              %td= link_to image_tag(picture.image, width: 100), picture.image.url
              %td= change_blank_to_dash(picture.description)
              %td
                .pull-right
                  = link_to icon('list-alt'), proprio_picture_path(proprio, picture), title: 'Détails', class: "btn btn-default"
                  = link_to icon('edit'), edit_proprio_picture_path(proprio, picture), title: 'Modifier', class: "btn btn-default"

    .pull-right
      = link_to 'Nouvelle image', new_proprio_picture_path(proprio), class: "btn btn-default"
      = link_to 'Vers le profil du propriétaire', proprio_path(proprio), class: 'btn btn-default'

    .flickr_pagination
      = will_paginate pictures

app/views/pictures/new.html.haml
.panel.panel-default
  .panel-heading Nouvelle image
  .panel-body
    = render 'form'

app/views/pictures/show.html.haml
.panel.panel-default
  .panel-heading Détails photos
  .panel-body
    .row
      .col-md-6
        = link_to image_tag(picture.image, width: 420), picture.image.url
      .col-md-6
        %table.table
          %tbody
            %tr
              %th.col-md-1 Nom:
              %td= change_blank_to_dash(picture.name)
            %tr
              %th.col-md-1 Propriétaire:
              %td= change_blank_to_dash(proprio.last_name.capitalize)
            %tr
              %th.col-md-1 Animal:
              %td= change_blank_to_dash(@animals)
            %tr
              %th.col-md-1 Description image:
              %td= change_blank_to_dash(picture.description)
            %tr
              %td
    .row
      .col-md-12
        .pull-right
          = link_to 'Aller à la galerie', proprio_pictures_path(proprio), class: 'btn btn-default'